echec_user:
    resource: "@EchecUserBundle/Resources/config/routing/routingAll.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

ed_blog_admin_feed:
    path:      /feed/{type}
    defaults:  { _controller: EDBlogBundle:Backend/Feed:feed }

ed_blog_frontend:
    resource: "@EDBlogBundle/Controller/Frontend/"
    type:     annotation
    prefix:   /

ed_blog:
    resource: "@EDBlogBundle/Controller/Backend/"
    type:     annotation
    prefix:   /blog/admin/

# Routing de base de FOSUser remplacé par echec_user
# fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"