echec_user:
    resource: "@EchecUserBundle/Resources/config/routing/routingAll.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Routing de base de FOSUser remplacé par echec_user
# fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"