# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
imports:
    - { resource: "@EchecUserBundle/Resources/config/security.yml" }

security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_USER: ROLE_BLOG_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_BLOG_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_BLOG_USER]

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }       